function makeStep(id, title, run, check, verify, rollback = []) {
  return { id, title, run, check, verify, rollback };
}

function renderScript(plan) {
  const lines = [
    '#!/usr/bin/env bash',
    'set -euo pipefail',
    '',
    `# ${plan.title}`,
    `# Generated by Home Base on ${plan.generatedAt}`,
    '',
  ];

  for (const step of plan.steps) {
    lines.push('echo', `echo "==> ${step.title}"`);
    for (const cmd of step.run) lines.push(cmd);
    lines.push('');
  }

  return `${lines.join('\n')}\n`;
}

function renderNginxGatewayRepairPython(defaultSitePath = '/etc/nginx/sites-available/default') {
  return `from pathlib import Path
default_site = Path(${JSON.stringify(defaultSitePath)})
text = default_site.read_text()
had_trailing_newline = text.endswith('\\n')
lines = text.splitlines()

def is_commented(line):
    return line.lstrip().startswith('#')

def has_active_line(fragment):
    return any(fragment in line and not is_commented(line) for line in lines)

def uncomment_default_line(fragment):
    for index, line in enumerate(lines):
        stripped = line.lstrip()
        indent = line[:len(line) - len(stripped)]
        if not stripped.startswith('#'):
            continue
        uncommented = stripped[1:].lstrip()
        if uncommented == fragment:
            lines[index] = indent + fragment
            return True
    return False

required_lines = [
    'listen 443 ssl default_server;',
    'listen [::]:443 ssl default_server;',
    'include snippets/snakeoil.conf;',
    'include /etc/nginx/snippets/*.conf;',
]

for fragment in required_lines:
    if not has_active_line(fragment):
        uncomment_default_line(fragment)

insertions = []
for fragment in required_lines:
    if not has_active_line(fragment):
        insertions.append('    ' + fragment)

if insertions:
    insert_at = None
    for index, line in enumerate(lines):
        if is_commented(line):
            continue
        if 'listen [::]:80 default_server;' in line:
            insert_at = index + 1
            break
        if 'listen 80 default_server;' in line:
            insert_at = index + 1
    if insert_at is None:
        for index, line in enumerate(lines):
            if line.strip() == 'server {':
                insert_at = index + 1
                break
    if insert_at is None:
        raise SystemExit('Could not find default nginx server block to configure')
    lines[insert_at:insert_at] = insertions

text = '\\n'.join(lines)
if had_trailing_newline:
    text += '\\n'
default_site.write_text(text)
`;
}

function renderSovereignFontSyncPython(sharedRoot = '/opt/sovereign-home') {
  return `import hashlib
import json
import re
from pathlib import Path
from urllib.request import Request, urlopen

root = Path(${JSON.stringify(sharedRoot)})
font_dir = root / 'assets' / 'fonts'
font_dir.mkdir(parents=True, exist_ok=True)

sources = [
    ('source-sans-3.css', 'https://fonts.googleapis.com/css2?family=Source+Sans+3:wght@400;500;600;700&display=swap'),
    ('jetbrains-mono.css', 'https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;600&display=swap'),
]

def fetch_text(url):
    req = Request(url, headers={'User-Agent': 'SovereignHomeFontSync/1.0'})
    with urlopen(req, timeout=30) as resp:
        return resp.read().decode('utf-8')

def fetch_bytes(url):
    req = Request(url, headers={'User-Agent': 'SovereignHomeFontSync/1.0'})
    with urlopen(req, timeout=30) as resp:
        return resp.read()

manifest = {'updated_at': None, 'files': []}
try:
    for css_name, css_url in sources:
        css = fetch_text(css_url)
        urls = re.findall(r"url\\\\((https://fonts\\\\.gstatic\\\\.com/[^)]+)\\\\)", css)
        rewritten = css
        for remote in sorted(set(urls)):
            data = fetch_bytes(remote)
            digest = hashlib.sha1(remote.encode('utf-8')).hexdigest()[:12]
            stem = remote.split('/')[-1].split('?')[0]
            local_name = f'{digest}-{stem}'
            (font_dir / local_name).write_bytes(data)
            rewritten = rewritten.replace(remote, f'./{local_name}')
            manifest['files'].append(local_name)
        (font_dir / css_name).write_text(rewritten)
        manifest['files'].append(css_name)
    manifest['updated_at'] = __import__('datetime').datetime.utcnow().isoformat() + 'Z'
    (font_dir / 'manifest.json').write_text(json.dumps(manifest, indent=2) + '\\\\n')
    print(f'[homebase] synced sovereign fonts to {font_dir}')
except Exception as exc:
    print(f'[homebase] sovereign font sync skipped: {exc}')
`;
}

function buildBootstrapPlan(input = {}) {
  const serviceUser = input.serviceUser || 'sovereign';
  const baseInstallDir = input.baseInstallDir || '/opt/sovereign-home/apps';
  const serviceUserHome = baseInstallDir.includes('/') ? baseInstallDir.slice(0, baseInstallDir.lastIndexOf('/')) : '/opt/sovereign-home';
  const sharedRoot = input.homeBaseSharedRoot || serviceUserHome || '/opt/sovereign-home';
  const assetsRoot = input.homeBaseAssetsRoot || `${sharedRoot}/assets`;
  const fontDir = `${assetsRoot}/fonts`;
  const baseBackupDir = input.baseBackupDir || '/var/lib/sovereign-home/backups';
  const baseConfigDir = input.baseConfigDir || '/etc/sovereign-home';
  const generatedAt = new Date().toISOString();
  const packages = [
    'git',
    'curl',
    'ca-certificates',
    'ssl-cert',
    'nginx',
    'postgresql',
    'postgresql-client',
    'nodejs',
    'python3',
    'python3-venv',
    'python3-pip',
  ];

  const steps = [
    makeStep(
      'verify-os',
      'Verify Debian-family host prerequisites',
      [
        'test -f /etc/debian_version',
        'command -v sudo >/dev/null 2>&1',
        'command -v systemctl >/dev/null 2>&1',
      ],
      ['test -f /etc/debian_version'],
      ['. /etc/os-release && echo "$PRETTY_NAME"']
    ),
    makeStep(
      'install-base-packages',
      'Install core system packages for Sovereign Home',
      [
        'sudo apt-get update',
        `sudo apt-get install -y ${packages.join(' ')}`,
        'if ! command -v npm >/dev/null 2>&1; then sudo apt-get install -y npm; fi',
      ],
      ['dpkg -s git >/dev/null 2>&1', 'dpkg -s nginx >/dev/null 2>&1', 'dpkg -s postgresql >/dev/null 2>&1'],
      ['node --version', 'python3 --version', 'psql --version', 'nginx -v']
    ),
    makeStep(
      'ensure-service-user',
      'Create the unprivileged service account used by managed apps',
      [
        `id -u ${serviceUser} >/dev/null 2>&1 || sudo useradd --system --create-home --home-dir ${serviceUserHome} --shell /usr/sbin/nologin ${serviceUser}`,
        `sudo install -d -m 0755 -o ${serviceUser} -g ${serviceUser} ${serviceUserHome}`,
        `sudo install -d -m 0755 -o ${serviceUser} -g ${serviceUser} ${serviceUserHome}/.npm`,
        `sudo install -d -m 0700 -o ${serviceUser} -g ${serviceUser} ${serviceUserHome}/.ssh`,
        `id -u homebase >/dev/null 2>&1 && sudo usermod -aG ${serviceUser} homebase || true`,
      ],
      [`id -u ${serviceUser} >/dev/null 2>&1`],
      [`id ${serviceUser}`]
    ),
    makeStep(
      'create-layout',
      'Create the Sovereign Home directory layout',
      [
        `sudo install -d -o ${serviceUser} -g ${serviceUser} ${baseInstallDir}`,
        `sudo install -d -o ${serviceUser} -g ${serviceUser} ${sharedRoot}`,
        `sudo install -d -o ${serviceUser} -g ${serviceUser} ${assetsRoot}`,
        `sudo install -d -o ${serviceUser} -g ${serviceUser} ${fontDir}`,
        `sudo install -d -o ${serviceUser} -g ${serviceUser} ${baseBackupDir}`,
        `sudo install -d -o root -g root ${baseConfigDir}`,
        `sudo install -d -o root -g root ${baseConfigDir}/manifests`,
        `sudo install -d -o root -g root ${baseConfigDir}/rendered`,
        'sudo install -d -o root -g root /etc/nginx/snippets',
      ],
      [`test -d ${baseInstallDir}`],
      [`sudo ls -ld ${baseInstallDir} ${sharedRoot} ${assetsRoot} ${fontDir} ${baseBackupDir} ${baseConfigDir} /etc/nginx/snippets`]
    ),
    makeStep(
      'configure-sovereign-font-assets',
      'Provision shared sovereign font assets and nginx route',
      [
        `sudo tee /etc/nginx/snippets/sovereign-fonts.conf > /dev/null <<'EOF'
location ^~ /_sovereign/fonts/ {
    alias ${fontDir}/;
    add_header Cache-Control "public, max-age=604800, immutable";
    add_header Access-Control-Allow-Origin "*";
    try_files $uri =404;
}
EOF`,
        `sudo python3 - <<'PY'
${renderSovereignFontSyncPython(sharedRoot)}
PY`,
      ],
      [
        `test -f /etc/nginx/snippets/sovereign-fonts.conf`,
        `test -f ${fontDir}/source-sans-3.css`,
        `test -f ${fontDir}/jetbrains-mono.css`,
      ],
      [
        `sudo ls -l ${fontDir}`,
        'sudo nginx -T | grep -n "/_sovereign/fonts/"',
      ]
    ),
    makeStep(
      'configure-nginx-gateway',
      'Ensure nginx includes managed app snippets from the default site',
      [
        `sudo python3 - <<'PY'
${renderNginxGatewayRepairPython()}
PY`,
      ],
      [
        `sudo nginx -T 2>/dev/null | grep -Fq "include /etc/nginx/snippets/*.conf;"`,
        `sudo nginx -T 2>/dev/null | grep -Fq "listen 443 ssl default_server;"`,
      ],
      [
        'sudo nginx -T | grep -n "/etc/nginx/snippets/*.conf;"',
        'sudo nginx -T | grep -n "listen 443 ssl default_server;"',
      ]
    ),
    makeStep(
      'enable-core-services',
      'Enable and start PostgreSQL and nginx',
      [
        'sudo systemctl enable --now postgresql',
        'sudo systemctl enable --now nginx',
        'sudo nginx -t',
        'sudo systemctl reload-or-restart nginx',
      ],
      ['systemctl is-enabled postgresql >/dev/null 2>&1', 'systemctl is-enabled nginx >/dev/null 2>&1'],
      ['systemctl is-active postgresql', 'systemctl is-active nginx']
    ),
    makeStep(
      'install-tailscale',
      'Install Tailscale if needed and enable tailscaled',
      [
        'command -v tailscale >/dev/null 2>&1 || curl -fsSL https://tailscale.com/install.sh | sh',
        'sudo systemctl enable --now tailscaled',
      ],
      ['command -v tailscale >/dev/null 2>&1'],
      ['tailscale version || true', 'systemctl is-active tailscaled || true']
    ),
    makeStep(
      'firewall-check',
      'Check firewall posture and allow nginx if ufw is active',
      [
        'if command -v ufw >/dev/null 2>&1; then if sudo ufw app info OpenSSH >/dev/null 2>&1; then sudo ufw allow OpenSSH || true; else sudo ufw allow 22/tcp || true; fi; fi',
        'if command -v ufw >/dev/null 2>&1 && sudo ufw status | grep -q "Status: active"; then sudo ufw allow "Nginx Full"; fi',
      ],
      ['true'],
      ['if command -v ufw >/dev/null 2>&1; then sudo ufw status verbose; else echo "ufw not installed"; fi']
    ),
  ];

  const plan = {
    kind: 'bootstrap',
    title: 'Home Base Debian bootstrap plan',
    generatedAt,
    assumptions: [
      'Target host is Debian or Ubuntu with sudo access.',
      'The operator wants systemd + nginx + PostgreSQL and Tailscale.',
      'Bootstrap is safe to re-run; all commands are written to be idempotent.',
    ],
    manualSteps: [
      'Run `sudo tailscale up` interactively if the host is not yet authenticated.',
      'Confirm MagicDNS or the desired tailnet hostname before publishing app links.',
    ],
    steps,
  };

  plan.script = renderScript(plan);
  return plan;
}

module.exports = {
  buildBootstrapPlan,
  renderNginxGatewayRepairPython,
};
