function makeStep(id, title, run, check, verify, rollback = []) {
  return { id, title, run, check, verify, rollback };
}

function renderScript(plan) {
  const lines = [
    '#!/usr/bin/env bash',
    'set -euo pipefail',
    '',
    `# ${plan.title}`,
    `# Generated by Home Base on ${plan.generatedAt}`,
    '',
  ];

  for (const step of plan.steps) {
    lines.push('echo', `echo "==> ${step.title}"`);
    for (const cmd of step.run) lines.push(cmd);
    lines.push('');
  }

  return `${lines.join('\n')}\n`;
}

function buildBootstrapPlan(input = {}) {
  const serviceUser = input.serviceUser || 'sovereign';
  const baseInstallDir = input.baseInstallDir || '/opt/sovereign-home/apps';
  const serviceUserHome = baseInstallDir.includes('/') ? baseInstallDir.slice(0, baseInstallDir.lastIndexOf('/')) : '/opt/sovereign-home';
  const baseBackupDir = input.baseBackupDir || '/var/lib/sovereign-home/backups';
  const baseConfigDir = input.baseConfigDir || '/etc/sovereign-home';
  const generatedAt = new Date().toISOString();
  const packages = [
    'git',
    'curl',
    'ca-certificates',
    'nginx',
    'postgresql',
    'postgresql-client',
    'nodejs',
    'npm',
    'python3',
    'python3-venv',
    'python3-pip',
  ];

  const steps = [
    makeStep(
      'verify-os',
      'Verify Debian-family host prerequisites',
      [
        'test -f /etc/debian_version',
        'command -v sudo >/dev/null 2>&1',
        'command -v systemctl >/dev/null 2>&1',
      ],
      ['test -f /etc/debian_version'],
      ['. /etc/os-release && echo "$PRETTY_NAME"']
    ),
    makeStep(
      'install-base-packages',
      'Install core system packages for Sovereign Home',
      [
        'sudo apt-get update',
        `sudo apt-get install -y ${packages.join(' ')}`,
      ],
      ['dpkg -s git >/dev/null 2>&1', 'dpkg -s nginx >/dev/null 2>&1', 'dpkg -s postgresql >/dev/null 2>&1'],
      ['node --version', 'python3 --version', 'psql --version', 'nginx -v']
    ),
    makeStep(
      'ensure-service-user',
      'Create the unprivileged service account used by managed apps',
      [
        `id -u ${serviceUser} >/dev/null 2>&1 || sudo useradd --system --create-home --home-dir ${serviceUserHome} --shell /usr/sbin/nologin ${serviceUser}`,
        `sudo install -d -m 0755 -o ${serviceUser} -g ${serviceUser} ${serviceUserHome}`,
        `sudo install -d -m 0755 -o ${serviceUser} -g ${serviceUser} ${serviceUserHome}/.npm`,
        `sudo install -d -m 0700 -o ${serviceUser} -g ${serviceUser} ${serviceUserHome}/.ssh`,
      ],
      [`id -u ${serviceUser} >/dev/null 2>&1`],
      [`id ${serviceUser}`]
    ),
    makeStep(
      'create-layout',
      'Create the Sovereign Home directory layout',
      [
        `sudo install -d -o ${serviceUser} -g ${serviceUser} ${baseInstallDir}`,
        `sudo install -d -o ${serviceUser} -g ${serviceUser} ${baseBackupDir}`,
        `sudo install -d -o root -g root ${baseConfigDir}`,
        `sudo install -d -o root -g root ${baseConfigDir}/manifests`,
        `sudo install -d -o root -g root ${baseConfigDir}/rendered`,
        'sudo install -d -o root -g root /etc/nginx/snippets',
      ],
      [`test -d ${baseInstallDir}`],
      [`sudo ls -ld ${baseInstallDir} ${baseBackupDir} ${baseConfigDir} /etc/nginx/snippets`]
    ),
    makeStep(
      'configure-nginx-gateway',
      'Ensure nginx includes managed app snippets from the default site',
      [
        `sudo python3 - <<'PY'
from pathlib import Path
default_site = Path('/etc/nginx/sites-available/default')
text = default_site.read_text()
include_line = '    include /etc/nginx/snippets/*.conf;'
if '/etc/nginx/snippets/*.conf;' not in text:
    marker = 'server_name _;'
    if marker not in text:
        raise SystemExit('Could not find server_name _; in nginx default site')
    text = text.replace(marker, marker + '\\n\\n' + include_line, 1)
    default_site.write_text(text)
PY`,
      ],
      [`sudo nginx -T 2>/dev/null | grep -Fq "include /etc/nginx/snippets/*.conf;"`],
      ['sudo nginx -T | grep -n "/etc/nginx/snippets/*.conf;"']
    ),
    makeStep(
      'enable-core-services',
      'Enable and start PostgreSQL and nginx',
      [
        'sudo systemctl enable --now postgresql',
        'sudo systemctl enable --now nginx',
      ],
      ['systemctl is-enabled postgresql >/dev/null 2>&1', 'systemctl is-enabled nginx >/dev/null 2>&1'],
      ['systemctl is-active postgresql', 'systemctl is-active nginx']
    ),
    makeStep(
      'install-tailscale',
      'Install Tailscale if needed and enable tailscaled',
      [
        'command -v tailscale >/dev/null 2>&1 || curl -fsSL https://tailscale.com/install.sh | sh',
        'sudo systemctl enable --now tailscaled',
      ],
      ['command -v tailscale >/dev/null 2>&1'],
      ['tailscale version || true', 'systemctl is-active tailscaled || true']
    ),
    makeStep(
      'firewall-check',
      'Check firewall posture and allow nginx if ufw is active',
      [
        'if command -v ufw >/dev/null 2>&1; then if sudo ufw app info OpenSSH >/dev/null 2>&1; then sudo ufw allow OpenSSH || true; else sudo ufw allow 22/tcp || true; fi; fi',
        'if command -v ufw >/dev/null 2>&1 && sudo ufw status | grep -q "Status: active"; then sudo ufw allow "Nginx Full"; fi',
      ],
      ['true'],
      ['if command -v ufw >/dev/null 2>&1; then sudo ufw status verbose; else echo "ufw not installed"; fi']
    ),
  ];

  const plan = {
    kind: 'bootstrap',
    title: 'Home Base Debian bootstrap plan',
    generatedAt,
    assumptions: [
      'Target host is Debian or Ubuntu with sudo access.',
      'The operator wants systemd + nginx + PostgreSQL and Tailscale.',
      'Bootstrap is safe to re-run; all commands are written to be idempotent.',
    ],
    manualSteps: [
      'Run `sudo tailscale up` interactively if the host is not yet authenticated.',
      'Confirm MagicDNS or the desired tailnet hostname before publishing app links.',
    ],
    steps,
  };

  plan.script = renderScript(plan);
  return plan;
}

module.exports = {
  buildBootstrapPlan,
};
