const SOVEREIGN_FONT_ENV_TEMPLATE = {
  SOVEREIGN_FONT_SOURCE: '{{sovereignFontSource}}',
  SOVEREIGN_FONT_SANS_CSS_URL: '{{sovereignFontSansCssUrl}}',
  SOVEREIGN_FONT_MONO_CSS_URL: '{{sovereignFontMonoCssUrl}}',
  SOVEREIGN_FONT_SANS_CSS_URL_LOCAL: '{{sovereignFontSansCssUrlLocal}}',
  SOVEREIGN_FONT_MONO_CSS_URL_LOCAL: '{{sovereignFontMonoCssUrlLocal}}',
};

const catalog = [
  {
    id: 'family-pulse',
    repoKey: 'familyPulse',
    name: 'Family Pulse',
    icon: '💰',
    purpose: 'Cash flow visibility, budgeting, and household financial awareness.',
    repository: {
      url: 'https://github.com/eforbell/familyPulse.git',
      sshUrl: 'git@github.com:eforbell/familyPulse.git',
      defaultRef: 'main',
    },
    runtime: {
      kind: 'node',
      installCommand: 'npm ci --omit=dev',
      startCommand: 'node server.js',
      nodeEnv: 'production',
    },
    network: {
      preferredMountPath: '/pulse/',
      preferredPort: 3003,
      upstreamBind: '127.0.0.1',
      health: {
        type: 'http',
        livenessPath: '/api/health',
        readinessPath: '/api/health',
      },
      notes: [
        'Plaid production OAuth requires a public HTTPS callback path.',
        'Current repo uses a second MCP sidecar service on port 3004.',
        'First-run household setup is handled in the browser when family_members is empty.',
      ],
    },
    database: {
      engine: 'postgres',
      bootstrap: 'migrations',
      databaseName: 'familypulse',
      databaseUser: 'familypulse',
      migrationCommand: 'node db/migrate.js',
      seedPolicy: 'app-onboarding',
    },
    onboarding: {
      mode: 'browser',
      setupPath: '/setup',
      statusPath: '/api/bootstrap',
      readyWhen: 'household_initialized',
      notes: [
        'No production db/seed.sql required; household and categories are created from the browser.',
        'Plaid credentials and passphrases are configured in Settings after first login.',
      ],
    },
    service: {
      name: 'family-pulse',
      description: 'Family Pulse App',
      envFile: '.env',
    },
    timers: [
      {
        serviceName: 'family-pulse-notifications',
        description: 'Family Pulse notification runner',
        execStart: 'node scripts/send-notifications.js',
        timerName: 'family-pulse-notifications.timer',
        onCalendar: '*:0/30',
      },
    ],
    sidecars: [
      {
        name: 'family-pulse-mcp',
        description: 'Family Pulse MCP Server',
        execStart: 'node mcp/server.js',
        env: {
          NODE_ENV: 'production',
        },
      },
    ],
    config: {
      env: {
        ...SOVEREIGN_FONT_ENV_TEMPLATE,
        DATABASE_URL: '{{databaseUrl}}',
        PORT: '{{port}}',
        PLAID_CLIENT_ID: '',
        PLAID_SECRET: '',
        PLAID_ENV: 'production',
        APP_URL: '{{externalUrl}}',
        PLAID_OAUTH_REDIRECT_URI: '{{publicUrl}}oauth/callback',
        OPENAI_API_KEY: '',
        OPENAI_MODEL: 'gpt-4o-mini',
        MCP_PORT: '{{sidecar.family-pulse-mcp.port}}',
        MCP_HOST: '127.0.0.1',
        MCP_AUTH_TOKEN: '',
        LOG_LEVEL: 'info',
        BOOTSTRAP_SECRET: '',
      },
    },
    storage: {
      paths: [],
    },
    updateNotes: [
      'Main app is a singleton because cron jobs run in-process.',
      'Use dedicated review for Plaid callback exposure before enabling production linking.',
    ],
  },
  {
    id: 'family-help',
    repoKey: 'familyHelp',
    name: 'Family Help',
    icon: '🤝',
    purpose: 'Household task intake, assignments, reminders, and first-tier help.',
    repository: {
      url: 'https://github.com/eforbell/familyHelp.git',
      sshUrl: 'git@github.com:eforbell/familyHelp.git',
      defaultRef: 'main',
    },
    runtime: {
      kind: 'node',
      installCommand: 'npm ci --omit=dev',
      startCommand: 'node server.js',
      nodeEnv: 'production',
    },
    network: {
      preferredMountPath: '/help/',
      preferredPort: 3002,
      upstreamBind: '127.0.0.1',
      health: {
        type: 'http',
        livenessPath: '/api/health',
        readinessPath: '/api/ready',
      },
      notes: [
        'First-run household setup is handled in the browser when family_members is empty.',
      ],
    },
    database: {
      engine: 'postgres',
      bootstrap: 'migrations',
      databaseName: 'familyhelp',
      databaseUser: 'familyhelp',
      migrationCommand: 'node db/migrate.js',
      seedPolicy: 'app-onboarding',
    },
    onboarding: {
      mode: 'browser',
      setupPath: '/setup',
      statusPath: '/api/bootstrap',
      readyWhen: 'household_initialized',
      notes: [
        'No production db/seed.sql is required; app bootstrap creates household and starter content from the browser.',
      ],
    },
    service: {
      name: 'family-help',
      description: 'Family Help App',
      envFile: '.env',
    },
    timers: [
      {
        serviceName: 'family-help-reminders',
        description: 'Family Help reminder runner',
        execStart: 'node scripts/send-reminders.js',
        timerName: 'family-help-reminders.timer',
        onCalendar: '*:0/30',
      },
      {
        serviceName: 'family-help-sweep',
        description: 'Family Help resolved ticket sweep',
        execStart: 'node scripts/sweep-resolved.js',
        timerName: 'family-help-sweep.timer',
        onCalendar: 'daily',
      },
    ],
    config: {
      env: {
        ...SOVEREIGN_FONT_ENV_TEMPLATE,
        DATABASE_URL: '{{databaseUrl}}',
        PORT: '{{port}}',
        OPENAI_API_KEY: '',
        OPENAI_MODEL: 'gpt-4o-mini',
        SETTINGS_PIN: '',
      },
    },
    storage: {
      paths: ['uploads'],
    },
    updateNotes: [
      'Back up repo-local uploads alongside PostgreSQL dumps.',
      'Reminder base URL should match the installed nginx/Tailscale address.',
    ],
  },
  {
    id: 'family-dinner',
    repoKey: 'familyDinner',
    name: 'Family Dinner',
    icon: '🍽️',
    purpose: 'Meal planning, recipes, rotation scheduling, and grocery helpers.',
    repository: {
      url: 'https://github.com/eforbell/familyDinner.git',
      sshUrl: 'git@github.com:eforbell/familyDinner.git',
      defaultRef: 'main',
    },
    runtime: {
      kind: 'node',
      installCommand: 'npm ci --omit=dev',
      startCommand: 'node server.js',
      nodeEnv: 'production',
    },
    network: {
      preferredMountPath: '/dinner/',
      preferredPort: 3000,
      upstreamBind: '127.0.0.1',
      health: {
        type: 'http',
        livenessPath: '/api/health',
        readinessPath: '/api/ready',
      },
      notes: [
        'First-run household setup is handled in the browser when family_members is empty.',
      ],
    },
    database: {
      engine: 'postgres',
      bootstrap: 'migrations',
      databaseName: 'family_dinner',
      databaseUser: 'family_dinner',
      migrationCommand: 'npm run db:migrate',
      seedPolicy: 'app-onboarding',
    },
    onboarding: {
      mode: 'browser',
      setupPath: '/setup',
      statusPath: '/api/bootstrap',
      readyWhen: 'household_initialized',
      notes: [
        'No production db/seed.sql is required; app bootstrap creates the first household from the browser.',
        'Starter order-in/default content can be installed during setup.',
      ],
    },
    service: {
      name: 'family-dinner',
      description: 'Family Dinner App',
      envFile: '.env',
    },
    config: {
      preserveExistingKeys: [
        'OPENAI_MODEL',
        'OPENAI_RECIPE_MODEL',
        'OPENAI_REASONING_EFFORT',
      ],
      env: {
        ...SOVEREIGN_FONT_ENV_TEMPLATE,
        DATABASE_URL: '{{databaseUrl}}',
        PORT: '{{port}}',
        OPENAI_API_KEY: '',
        OPENAI_MODEL: 'gpt-5.4-nano',
        OPENAI_RECIPE_MODEL: 'gpt-5.4-nano',
        OPENAI_REASONING_EFFORT: 'none',
        RECIPE_IMPORT_USER_AGENT: 'Home Base importer/0.1',
      },
    },
    storage: {
      paths: [],
    },
    updateNotes: [
      'Do not run db/seed.sql in production installs; it is destructive sample data.',
    ],
  },
  {
    id: 'family-plan',
    repoKey: 'familyPlan',
    name: 'Family Plan',
    icon: '📅',
    purpose: 'Family calendar aggregation, daily briefings, and optional Google writeback.',
    repository: {
      url: 'https://github.com/eforbell/familyPlan.git',
      sshUrl: 'git@github.com:eforbell/familyPlan.git',
      defaultRef: 'main',
    },
    runtime: {
      kind: 'node',
      installCommand: 'npm ci --omit=dev',
      startCommand: 'node server.js',
      nodeEnv: 'production',
    },
    network: {
      preferredMountPath: '/plan/',
      preferredPort: 3001,
      upstreamBind: '127.0.0.1',
      health: {
        type: 'http',
        livenessPath: '/api/health',
        readinessPath: '/api/ready',
      },
      notes: [
        'Explicit GOOGLE_REDIRECT_URI is recommended when using a subpath proxy.',
        'First-run household setup is handled in the browser when family_members is empty.',
      ],
    },
    database: {
      engine: 'postgres',
      bootstrap: 'migrations',
      databaseName: 'familyplan',
      databaseUser: 'familyplan',
      migrationCommand: 'node db/migrate.js',
      seedPolicy: 'app-onboarding',
    },
    onboarding: {
      mode: 'browser',
      setupPath: '/setup',
      statusPath: '/api/bootstrap',
      readyWhen: 'household_initialized',
      notes: [
        'No production db/seed.sql is required; app bootstrap creates the first household from the browser.',
      ],
    },
    service: {
      name: 'family-plan',
      description: 'Family Plan App',
      envFile: '.env',
    },
    timers: [
      {
        serviceName: 'family-plan-reminders',
        description: 'Family Plan reminder runner',
        execStart: 'node scripts/send-reminders.js',
        timerName: 'family-plan-reminders.timer',
        onCalendar: '*-*-* 07:00:00',
      },
    ],
    config: {
      env: {
        ...SOVEREIGN_FONT_ENV_TEMPLATE,
        DATABASE_URL: '{{databaseUrl}}',
        PORT: '{{port}}',
        OPENAI_API_KEY: '',
        OPENAI_MODEL: 'gpt-4o-mini',
        GOOGLE_CLIENT_ID: '',
        GOOGLE_CLIENT_SECRET: '',
        GOOGLE_REDIRECT_URI: '{{externalUrl}}api/google-calendar/oauth/callback',
        SETTINGS_PIN: '',
        CALENDAR_WRITE_PIN: '',
        HOUSEHOLD_TIMEZONE: '{{householdTimezone}}',
      },
    },
    storage: {
      paths: [],
    },
    updateNotes: [
      'Important runtime config also lives in app_config; env alone is not the full state.',
      'Do not run db/seed.sql automatically for production households.',
    ],
  },
  {
    id: 'fast-to-eat',
    repoKey: 'fastToEat',
    name: 'Fast to Eat',
    icon: '⏱️',
    purpose: 'Intermittent fasting check-ins, streaks, and eating-window reminders for the household.',
    repository: {
      url: 'https://github.com/eforbell/fastToEat.git',
      sshUrl: 'git@github.com:eforbell/fastToEat.git',
      defaultRef: 'main',
    },
    runtime: {
      kind: 'node',
      installCommand: 'npm ci --omit=dev',
      startCommand: 'node server.js',
      nodeEnv: 'production',
    },
    network: {
      preferredMountPath: '/fte/',
      preferredPort: 3007,
      upstreamBind: '127.0.0.1',
      health: {
        type: 'http',
        livenessPath: '/api/health',
        readinessPath: '/api/health',
      },
      notes: [
        'First-run household setup is handled in the browser when family_members is empty.',
        'All fetch() calls and asset refs are relative so nginx subpath mounting at /fte/ works.',
      ],
    },
    database: {
      engine: 'postgres',
      bootstrap: 'migrations',
      databaseName: 'fasttoeat',
      databaseUser: 'fasttoeat',
      migrationCommand: 'node db/migrate.js',
      seedPolicy: 'app-onboarding',
    },
    onboarding: {
      mode: 'browser',
      setupPath: '/setup',
      statusPath: '/api/bootstrap',
      readyWhen: 'household_initialized',
    },
    service: {
      name: 'fast-to-eat',
      description: 'Fast to Eat App',
      envFile: '.env',
    },
    timers: [
      {
        serviceName: 'fast-to-eat-reminders',
        description: 'Fast to Eat reminder runner',
        execStart: 'node scripts/send-reminders.js',
        timerName: 'fast-to-eat-reminders.timer',
        onCalendar: '*:0/15',
      },
    ],
    config: {
      env: {
        ...SOVEREIGN_FONT_ENV_TEMPLATE,
        DATABASE_URL: '{{databaseUrl}}',
        PORT: '{{port}}',
        HOUSEHOLD_TIMEZONE: '{{householdTimezone}}',
        APP_PUBLIC_URL: '{{externalUrl}}',
        LOG_LEVEL: 'info',
      },
    },
    storage: {
      paths: [],
    },
    updateNotes: [
      'Reminder timer de-dupes per (member, event, date) via notification_event_state; do not run more than one instance.',
      'Per-member brrr secrets are stored in member_notification_channels and configured from Settings, not env.',
    ],
  },
  {
    id: 'bitcoin-accounting',
    repoKey: 'bitcoinAccounting',
    name: 'Bitcoin Accounting',
    icon: '🪙',
    purpose: 'Treasury management, tax reporting, and attestation for sovereign bitcoin holdings.',
    repository: {
      url: 'https://github.com/eforbell/bitcoinAccounting.git',
      sshUrl: 'git@github.com:eforbell/bitcoinAccounting.git',
      defaultRef: 'master',
    },
    runtime: {
      kind: 'python',
      installCommand: '.venv/bin/python -m pip install -e .',
      startCommand: '.venv/bin/uvicorn web.app:create_app --factory --host 127.0.0.1 --port {{port}}',
      pythonVenv: '.venv',
    },
    network: {
      preferredMountPath: '/bitcoin-accounting/',
      preferredPort: 3010,
      preserveMountPath: true,
      upstreamBind: '127.0.0.1',
      health: {
        type: 'http',
        livenessPath: '/api/health',
        readinessPath: '/api/ready',
      },
      notes: [
        'Reverse proxy must strip the external subpath before proxying upstream.',
      ],
    },
    database: {
      engine: 'postgres-or-sqlite',
      bootstrap: 'schema-file',
      databaseName: 'bitcoin_accounting',
      databaseUser: 'bitcoin_accountant',
      schemaCommand: 'psql -d {{dbName}} -f src/sql/tables.sql',
      migrationCommand: '.venv/bin/bitcoin-accounting-web-init',
      seedPolicy: 'never',
    },
    service: {
      name: 'bitcoin-accounting-web',
      description: 'Bitcoin Accounting Web API',
      envFile: '.env',
    },
    config: {
      // Operator-tuned chain-status flags have non-empty catalog defaults, so they
      // would otherwise be reset on every update; preserve the operator's choice.
      preserveExistingKeys: ['BITCOIN_CHAIN_STATUS_ENABLED', 'BITCOIN_RPC_TIMEOUT_SECONDS'],
      env: {
        ...SOVEREIGN_FONT_ENV_TEMPLATE,
        DB_BACKEND: 'postgres',
        PGHOST: '127.0.0.1',
        PGPORT: '5432',
        PGUSER: '{{dbUser}}',
        PGPASSWORD: '{{dbPassword}}',
        PGDATABASE: '{{dbName}}',
        BITCOIN_ACCOUNTING_ENV: 'production',
        BITCOIN_ACCOUNTING_WEB_BASE_PATH: '{{mountBasePath}}',
        BITCOIN_ACCOUNTING_WEB_DOCS: '0',
        BITCOIN_ACCOUNTING_WEB_ALLOW_SQLITE: '0',
        BITCOIN_ACCOUNTING_AUTH_ENABLED: '1',
        BITCOIN_ACCOUNTING_AUTH_PASSPHRASE: '{{secret1}}',
        BITCOIN_ACCOUNTING_SESSION_SECRET: '{{secret2}}',
        BITCOIN_ACCOUNTING_SESSION_COOKIE: 'ba_session',
        BITCOIN_ACCOUNTING_SESSION_TTL_SECONDS: '604800',
        BITCOIN_CHAIN_STATUS_ENABLED: '0',
        BITCOIN_RPC_URL: '',
        BITCOIN_RPC_COOKIE_FILE: '',
        BITCOIN_RPC_USER: '',
        BITCOIN_RPC_PASSWORD: '',
        BITCOIN_RPC_TIMEOUT_SECONDS: '3',
      },
    },
    storage: {
      paths: [],
    },
    updateNotes: [
      'Prefer repo-local virtualenvs over system Python.',
      'PostgreSQL installs must run src/sql/tables.sql before the web init command.',
    ],
  },
  {
    id: 'helm',
    repoKey: 'helm',
    name: 'Helm',
    icon: '⚓',
    purpose: 'Schwab-based investment advisor for read-only monitoring, goal tracking, and operator-approved recommendations.',
    repository: {
      url: 'https://github.com/eforbell/helm.git',
      sshUrl: 'git@github.com:eforbell/helm.git',
      defaultRef: 'main',
    },
    runtime: {
      kind: 'python',
      installCommand: 'install -d -m 0700 .secrets && .venv/bin/python -m pip install -r requirements.lock && .venv/bin/python -m pip install -e . --no-deps',
      startCommand: '.venv/bin/uvicorn schwab_helm.web.app:create_app --factory --host 127.0.0.1 --port {{port}}',
      pythonVenv: '.venv',
    },
    network: {
      preferredMountPath: '/helm/',
      preferredPort: 3011,
      preserveMountPath: true,
      upstreamBind: '127.0.0.1',
      health: {
        type: 'http',
        livenessPath: '/health',
        readinessPath: '/health',
      },
      notes: [
        'HomeBase preserves the /helm/ mount path when proxying; Helm must tolerate HELM_WEB_BASE_PATH=/helm on incoming requests.',
        'Schwab has no sandbox, so production installs should keep Helm read-only until order placement is deliberately reviewed.',
        'Schwab OAuth callback may need a dedicated HTTPS host that routes to Helm /oauth/callback.',
      ],
    },
    database: {
      engine: 'postgres',
      bootstrap: 'migrations',
      databaseName: 'helm',
      databaseUser: 'helm',
      urlEnvKey: 'HELM_DATABASE_URL',
      migrationCommand: '.venv/bin/python migrations/run_migration.py',
      seedPolicy: 'never',
    },
    service: {
      name: 'helm-web',
      description: 'Helm Schwab investment advisor web API',
      envFile: '.env',
      umask: '0077',
    },
    timers: [
      {
        serviceName: 'helm-sync',
        description: 'Helm daily account/position sync',
        execStart: '.venv/bin/helm sync',
        timerName: 'helm-sync.timer',
        onCalendar: 'Mon..Fri 08:00',
      },
      {
        serviceName: 'helm-review',
        description: 'Helm weekly portfolio review',
        execStart: '.venv/bin/helm review --trigger weekly --if-due',
        timerName: 'helm-review.timer',
        onCalendar: 'Mon 08:15',
      },
      {
        serviceName: 'helm-monitor',
        description: 'Helm turbulence monitor',
        execStart: '.venv/bin/helm-monitor',
        timerName: 'helm-monitor.timer',
        onCalendar: 'Mon..Fri 09..16:00/30',
        persistent: false,
      },
      {
        serviceName: 'helm-token-refresh',
        description: 'Helm Schwab access-token refresh and token health probe',
        execStart: '.venv/bin/helm refresh-token',
        timerName: 'helm-token-refresh.timer',
        onCalendar: '*-*-* 07:30',
      },
    ],
    config: {
      preserveExistingKeys: [
        'ADVISOR_PROVIDER',
        'ADVISOR_MODEL',
        'HELM_MODEL_SYNTHESIS_ENABLED',
      ],
      env: {
        ...SOVEREIGN_FONT_ENV_TEMPLATE,
        HELM_ENV: 'production',
        HELM_WEB_BASE_PATH: '{{mountBasePath}}',
        HELM_WEB_HOST: '127.0.0.1',
        HELM_WEB_PORT: '{{port}}',
        HELM_WEB_DOCS: '0',
        HELM_DATABASE_URL: '{{databaseUrl}}',
        HELM_TEST_DATABASE_URL: '',
        SCHWAB_APP_KEY: '',
        SCHWAB_APP_SECRET: '',
        SCHWAB_CALLBACK_URL: '',
        SCHWAB_TOKEN_PATH: './.secrets/schwab_tokens.db',
        ADVISOR_PROVIDER: 'openai',
        ADVISOR_MODEL: 'gpt-4o-mini',
        HELM_MODEL_SYNTHESIS_ENABLED: '1',
        OPENAI_API_KEY: '',
        BRRR_SECRET: '',
        HELM_PUBLIC_URL: '{{externalUrl}}',
        MONITOR_POSITION_MOVE_PCT: '7',
        MONITOR_PORTFOLIO_DRAWDOWN_PCT: '4',
        MONITOR_COOLDOWN_MINUTES: '180',
        HELM_AUTH_ENABLED: '1',
        HELM_AUTH_PASSPHRASE: '{{secret1}}',
        HELM_SESSION_SECRET: '{{secret2}}',
        HELM_SESSION_COOKIE: 'helm_session',
        HELM_SESSION_TTL_SECONDS: '604800',
        LOG_LEVEL: 'info',
      },
    },
    storage: {
      paths: ['.secrets'],
    },
    updateNotes: [
      'No Schwab sandbox exists: keep SCHWAB_APP_KEY/SECRET and token storage out of git and preserve .env across reinstalls.',
      'Manual .env completion and service restart are expected until Helm gets a browser setup mode.',
      'Weekly Schwab browser re-auth remains required; the token-refresh timer does not extend the 7-day refresh-token cap.',
      'Backup .secrets with the database because SCHWAB_TOKEN_PATH stores live OAuth tokens.',
    ],
  },
  {
    id: 'home-source',
    repoKey: 'homeSource',
    name: 'Home Source',
    icon: '📁',
    purpose: 'Sovereign family document vault — store, organize, and protect household records.',
    repository: {
      url: 'https://github.com/eforbell/homeSource.git',
      sshUrl: 'git@github.com:eforbell/homeSource.git',
      defaultRef: 'main',
    },
    runtime: {
      kind: 'node',
      installCommand: 'npm ci --omit=dev',
      startCommand: 'node server.js',
      nodeEnv: 'production',
    },
    systemPackages: ['poppler-utils', 'tesseract-ocr'],
    network: {
      preferredMountPath: '/source/',
      preferredPort: 3008,
      upstreamBind: '127.0.0.1',
      health: {
        type: 'http',
        livenessPath: '/api/health',
        readinessPath: '/api/ready',
      },
      notes: [
        'Set client_max_body_size 55M in the nginx location block to allow large document uploads.',
        'First-run household setup is handled in the browser when family_members is empty.',
        'Share links at /share/:token are public routes — no auth required.',
      ],
    },
    database: {
      engine: 'postgres',
      bootstrap: 'migrations',
      databaseName: 'homesource',
      databaseUser: 'homesource',
      migrationCommand: 'node db/migrate.js',
      seedPolicy: 'app-onboarding',
    },
    onboarding: {
      mode: 'browser',
      setupPath: '/setup',
      statusPath: '/api/bootstrap',
      readyWhen: 'household_initialized',
      notes: [
        'No production seed required; household is created from the browser.',
        'Passphrases are set per-member during or after setup.',
      ],
    },
    service: {
      name: 'home-source',
      description: 'Home Source App',
      envFile: '.env',
    },
    sidecars: [
      {
        name: 'home-source-import-worker',
        description: 'Home Source Import Worker',
        execStart: 'node bin/import-worker.js',
        env: {
          NODE_ENV: 'production',
        },
      },
    ],
    config: {
      env: {
        ...SOVEREIGN_FONT_ENV_TEMPLATE,
        DATABASE_URL: '{{databaseUrl}}',
        PORT: '{{port}}',
        STORAGE_PATH: '/var/lib/sovereign-home/home-source/data',
        HOUSEHOLD_TIMEZONE: '{{householdTimezone}}',
        MAX_FILE_SIZE_MB: '50',
      },
    },
    storage: {
      absoluteRoot: '/var/lib/sovereign-home/home-source/data',
      paths: ['documents', 'thumbnails', 'exports'],
    },
    updateNotes: [
      'The STORAGE_PATH directory must exist and be writable by the service user before first start.',
      'Back up the STORAGE_PATH directory alongside PostgreSQL dumps — documents live on disk, not in the database.',
      'Backup exports are written to data/exports/ and can be downloaded from the Backup page.',
      'Encryption schema (encryption_keys, key_holders) is present but unused until day-2 features land.',
    ],
  },
  {
    id: 'bug-base',
    repoKey: 'bugBase',
    name: 'Bug Base',
    icon: '🐛',
    purpose: 'Household bug tracker and feature request log with an MCP sidecar for agent access.',
    repository: {
      url: 'https://github.com/eforbell/bugBase.git',
      sshUrl: 'git@github.com:eforbell/bugBase.git',
      defaultRef: 'main',
    },
    runtime: {
      kind: 'node',
      installCommand: 'npm ci --omit=dev',
      startCommand: 'node server.js',
      nodeEnv: 'production',
    },
    network: {
      preferredMountPath: '/bugs/',
      preferredPort: 3005,
      upstreamBind: '127.0.0.1',
      health: {
        type: 'http',
        livenessPath: '/api/health',
        readinessPath: '/api/health',
      },
      notes: [
        'MCP sidecar runs on a separate port; expose it behind a protected nginx lane if needed.',
        'Set client_max_body_size 12M in the nginx location block to allow screenshot uploads.',
      ],
    },
    database: {
      engine: 'postgres',
      bootstrap: 'migrations',
      databaseName: 'bugbase',
      databaseUser: 'bugbase',
      migrationCommand: 'node db/migrate.js',
      seedPolicy: 'browser-setup',
    },
    service: {
      name: 'bug-base',
      description: 'Bug Base App',
      envFile: '.env',
    },
    sidecars: [
      {
        name: 'bug-base-mcp',
        description: 'Bug Base MCP Server',
        execStart: 'node mcp/server.js',
        env: {
          NODE_ENV: 'production',
        },
        nginx: {
          mountPathSuffix: 'mcp/',
          upstreamPath: '/mcp/',
        },
      },
    ],
    config: {
      env: {
        ...SOVEREIGN_FONT_ENV_TEMPLATE,
        DATABASE_URL: '{{databaseUrl}}',
        PORT: '{{port}}',
        MCP_PORT: '{{sidecar.bug-base-mcp.port}}',
        MCP_HOST: '127.0.0.1',
        BUGBASE_AGENT_TOKENS: '',
        BUGBASE_MCP_AUTH_TOKEN: '',
        BUGBASE_BROWSER_ACCESS_CODE: '',
      },
    },
    storage: {
      paths: ['uploads'],
    },
    updateNotes: [
      'Run node db/migrate.js after every deploy — deploy/deploy.sh does this automatically.',
      'Seed migration (002) inserts family members and app rows; add new apps via additional migrations.',
      'BUGBASE_BROWSER_ACCESS_CODE is optional; leave blank for open family-LAN access.',
    ],
  },
  {
    id: 'home-ops',
    repoKey: 'homeOps',
    name: 'Home Ops',
    icon: '🔧',
    purpose: 'Home maintenance management — recurring tasks, asset tracking, service records, photo documentation, and emergency preparedness.',
    repository: {
      url: 'https://github.com/eforbell/homeOps.git',
      sshUrl: 'git@github.com:eforbell/homeOps.git',
      defaultRef: 'main',
    },
    runtime: {
      kind: 'node',
      installCommand: 'npm ci --omit=dev',
      startCommand: 'node server.js',
      nodeEnv: 'production',
    },
    network: {
      preferredMountPath: '/ops/',
      preferredPort: 3009,
      upstreamBind: '127.0.0.1',
      health: {
        type: 'http',
        livenessPath: '/api/health',
        readinessPath: '/api/ready',
      },
      notes: [
        'First-run household setup is handled in the browser when family_members is empty.',
        'Set client_max_body_size 20M in the nginx location block for photo uploads.',
        'iCal feed at /api/calendar.ics is unauthenticated for calendar subscription.',
      ],
    },
    database: {
      engine: 'postgres',
      bootstrap: 'migrations',
      databaseName: 'homeops',
      databaseUser: 'homeops',
      migrationCommand: 'node db/migrate.js',
      seedPolicy: 'app-onboarding',
    },
    onboarding: {
      mode: 'browser',
      setupPath: '/setup',
      statusPath: '/api/bootstrap',
      readyWhen: 'household_initialized',
      notes: [
        'Six-step wizard creates household, property, zones, assets, and emergency contacts.',
        'Seed maintenance schedules are generated from zone config during onboarding.',
        'MagicMaintenance (OpenAI) can generate additional schedules post-onboarding.',
      ],
    },
    service: {
      name: 'home-ops',
      description: 'Home Ops App',
      envFile: '.env',
    },
    timers: [
      {
        serviceName: 'home-ops-reminders',
        description: 'Home Ops reminder runner',
        execStart: 'node scripts/send-reminders.js',
        timerName: 'home-ops-reminders.timer',
        onCalendar: '*:0/30',
      },
      {
        serviceName: 'home-ops-tasks',
        description: 'Home Ops task instance generator',
        execStart: 'node scripts/generate-task-instances.js',
        timerName: 'home-ops-tasks.timer',
        onCalendar: '*-*-* 05:00:00',
      },
    ],
    config: {
      env: {
        ...SOVEREIGN_FONT_ENV_TEMPLATE,
        DATABASE_URL: '{{databaseUrl}}',
        PORT: '{{port}}',
        HOUSEHOLD_TIMEZONE: '{{householdTimezone}}',
        SETTINGS_PIN: '',
        OPENAI_API_KEY: '',
        OPENAI_MODEL: 'gpt-4o-mini',
        OPENAI_VISION_MODEL: 'gpt-4o',
      },
    },
    storage: {
      paths: ['uploads'],
    },
    updateNotes: [
      'Run node db/migrate.js after every deploy.',
      'Two systemd timers must be enabled: home-ops-reminders.timer (30min) and home-ops-tasks.timer (daily 5AM).',
      'OPENAI_API_KEY is optional — MagicMaintenance and photo analysis degrade gracefully without it.',
    ],
  },
];

function getCatalog() {
  return catalog.slice();
}

function getAppById(id) {
  return catalog.find((entry) => entry.id === id) || null;
}

module.exports = {
  catalog,
  getCatalog,
  getAppById,
};
